### ISSUE TITLE
README changes

### ISSUE THREAD

**Issue by dylmye** [joehoyle/monzo-to-lunch-money#9]
Hi! Thanks for writing this package. I haven't used Serverless before. I think it would be useful to have a prerequisites list in the README. Something like the below:

* Serverless CLI v2
* [Monzo OAuth Client](https://developers.monzo.com)

and maybe some of the obvious like a Monzo account (does the Monzo API work for [Monzo USA](https://monzo.com/us/) accounts? If not it would be good to specify).

Also I don't see what the point of step 2 in your current list is, because we don't do anything with the monzo account ID?

Thank you :)

**Comment by dylmye** [comment]
Also I tried to run the following command after `yarn global add serverless@1`:
```
$env:LUNCHMONEY_ASSET_ID=XXX;$env:LUNCHMONEY_TOKEN=XXX;$env:MONZO_CLIENT_ID=XXX;$env:MONZO_CLIENT_SECRET=XXX; serverless deploy --org=FOOBAR --stage production --region eu-west-2
```

And I get the following error back:
```
Error: Profile sub_account does not exist
      at Object.addProfileCredentials (C:\Users\XXX\AppData\Local\Yarn\Data\global\node_modules\serverless\lib\plugins\aws\provider\awsProvider.js:106:15)
      at AwsProvider.getCredentials (C:\Users\XXX\AppData\Local\Yarn\Data\global\node_modules\serverless\lib\plugins\aws\provider\awsProvider.js:667:12)
```
Let me know if I can provide any details to help
